### DISCUSSION TITLE
How to switch from validator/validator to ghcr.io/validator/validator

### DISCUSSION THREAD

**Discussion by ptmkenny** [validator/validator#1182] [Q&A] [answered]
I've been using [Lando](https://github.com/lando/lando/releases) with validator/validator for a couple years, but today, when I rebuild my local development environment, I couldn't pull from `validator/validator`.  I checked the documentation, and it seems that the docker image is now at `ghcr.io/validator/validator`.

I downloaded the new image but it no longer works.

Here's my original lando config:

```
  vnu:
    # https://github.com/lando/lando/issues/2731
    type: compose
    ssl: true
    sslExpose: false
    services:
      image: validator/validator:20.6.30
      command: java -cp ~/vnu.jar nu.validator.servlet.Main 8888
      ports:
        - '8888:8888'
```

And here's what I tried with the new image:

```
  vnu:
    # https://github.com/lando/lando/issues/2731
    type: compose
    ssl: true
    sslExpose: false
    services:
      image: ghcr.io/validator/validator:latest
      command: java -cp ~/vnu.jar nu.validator.servlet.Main 8888
      ports:
        - '8888:8888'
```

Any ideas about how to get this working again would be much appreciated.
