### ISSUE TITLE
Incorrect validation: woff2 is a widely supported format

### ISSUE THREAD

**Issue by philoserf** [validator/validator#1144]
https://markpaulayers.com/

```
Error: CSS: src: woff2 is not a format value
```

**Comment by sideshowbarker** [comment]
I can’t reproduce — https://validator.w3.org/nu/?doc=https://markpaulayers.com/ doesn’t show that error  (nor any other errors)

**Comment by philoserf** [comment]
I removed the font temporarily.  I’ll be putting it back tomorrow, Monday.

**Comment by philoserf** [comment]
I went ahead and put it back now.

**Comment by philoserf** [comment]
CSS Snippet

```css
@font-face {
  font-family: "opendyslexic";
  src: url("../fonts/OpenDyslexic-Regular.woff2") format(woff2),
    url("../fonts/OpenDyslexic-Regular.woff") format(woff),
    url("../fonts/OpenDyslexic-Regular.otf") format(otf);
  font-style: normal;
  font-weight: normal;
  font-display: swap;
}

@font-face {
  font-family: "opendyslexic-mono";
  src: url("../fonts/OpenDyslexicMono-Regular.woff2") format(woff2),
    url("../fonts/OpenDyslexicMono-Regular.woff") format(woff),
    url("../fonts/OpenDyslexicMono-Regular.otf") format(otf);
  font-weight: normal;
  font-display: swap;
}

* {
  font-family: "opendyslexic", Fallback, sans-serif !important;
}
```
