### ISSUE TITLE
Grammar validation(Pseudo classes) support

### ISSUE THREAD

**Issue by stefango** [validator/validator#1159]
https://github.com/less/less.js/issues/3620
https://validator.w3.org/nu/#textarea
```css
// wrong（no error reported in this validator）
:not(first-child) {
  background: red;
}

// correct
:not(:first-child) {
  background: red;
}
```
