### ISSUE TITLE
[CSS] repeating-linear-gradient, space char is an incorrect operator

### ISSUE THREAD

**Issue by T1mL3arn** [validator/validator#1218]
Code to reproduce error:

```css
body {
  background-image: repeating-linear-gradient(-45deg,
      transparent 0 20px,
      black 20px 40px);
}
```

Error message:

```
Error: background-image:  is an incorrect operator.

At line 4, column 22
```

Validator says space char (char with code 32) is an incorrect operator.

Original code example from mdn page - https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/repeating-linear-gradient()#zebra_stripes
