### ISSUE TITLE
[CSS] background-image: too few values for the property linear-gradient

### ISSUE THREAD

**Issue by onlime** [validator/validator#1224]
URL being validated or code to reproduce error: https://pipo.blog

```
Error:
CSS: background-image: too few values for the property linear-gradient.
At line 4, column 25252
```

Experiencing this validation issue with Tailwind CSS, which actually produces valid CSS, see https://github.com/tailwindlabs/tailwindcss/issues/5349#issuecomment-910255469

Code to reproduce:

```css
/* With variable */
.foo {
  --gradient-stops: #000, #fff;
  background-image:linear-gradient(to right, var(--tw-gradient-stops));
}

/* Computed as */
.foo {
  background-image:linear-gradient(to right, #000, #fff);
}
```
