### ISSUE TITLE
Outline color validation don't allow using variables

### ISSUE THREAD

**Issue by leio10** [validator/validator#1233]
When validating the following CSS3 block:
```css
  .style {
    --focus-indicator-color: #999999;
  }
  
  .style:focus {
    outline: 1px dotted var(--focus-indicator-color);
  }
```

The [online service](http://jigsaw.w3.org/css-validator/validator) returns the message:
```
CSS: “outline”: “var(--focus-indicator-color)” is not a valid color 3 or 6 hexadecimals numbers.
```

Is this correct? The style is working properly on Firefox. I also tried with `outline-color` and it also fails. It seems that the outline color is not well defined, as it works when replacing `outline` with `border`.

Thanks for your awesome work! ❤️
