### ISSUE TITLE
Docker image gives ERR_EMPTY_RESPONSE after updating Docker on new MBP M1

### ISSUE THREAD

**Issue by Brade** [validator/validator#1279]
This past week I was able to pull the Docker image and get it running on a new Macbook Pro (not always easy with certain images as you probably know because of the new M1 chip). But today Docker updated itself, claiming it no longer needs Rosetta 2 to work. This may or may not be the reason for the Docker image suddenly not working, but I thought I'd post an issue here just in case. I find this project very useful!

I didn't do anything funky, just pulled the latest Docker image and used it with the following docker-compose.yml (my various other docker images still work fine)

```
services:
  vnu:
    image: ghcr.io/validator/validator:latest
    ports:
      - "127.0.0.1:8888:8888"

```
