### ISSUE TITLE
Incorrect validation of css calc in combination with var

### ISSUE THREAD

**Issue by tkalmar** [validator/validator#1284]
```
<!DOCTYPE html>
<html lang="">
<head>
<title>Test</title>
<style>
  #some {
    --myvar: 0;
    margin-top: calc(0px * (1 - var(--myvar)));
    margin-bottom: calc(0px * var(--myvar));
  }

</style>
</head>
<body>
</body>
</html>
```

```
    Error: CSS: margin-top: The types are incompatible.

    At line 8, column 46

    - var(--myvar)));↩    margin-b

    Error: CSS: margin-bottom: One operand must be a number.

    At line 9, column 43

     * var(--myvar));↩  }↩↩</style
```

**Comment by nschonni** [comment]
I'm guessing this is an issue with https://github.com/w3c/css-validator

**Comment by tkalmar** [comment]
Duplicate of https://github.com/w3c/css-validator/issues/355

**Comment by ahukkanen** [comment]
@nschonni This is actually already fixed at https://github.com/w3c/css-validator as explained at https://github.com/w3c/css-validator/issues/355.

The actual problem is that the HTML Nu validator does not include the latest changes in the CSS validator.

**Comment by tkalmar** [comment]
The used version of css validator should be updated.

**Comment by nschonni** [comment]
Looking at the diff https://github.com/w3c/css-validator/compare/validator-nu i'm not sure if there is anything critical that is needed if the submodule pointed to the default branch

**Comment by tkalmar** [comment]
@nschonni see: https://github.com/w3c/css-validator/issues/355#issuecomment-991717512

**Comment by ahukkanen** [comment]
Any idea when we could get the CSS validator updated for the HTML nu validator? See issue w3c/css-validator#355 for details which explains why the problems only exist at the HTML validator and not in the CSS validator.

Here's another example you can try at the [Nu HTML validator](https://validator.w3.org/nu/#textarea):

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Test</title>
<style>
:root {
  --emoji-size: 2rem;
  --emoji-size-multiplier: 1.3;
  --emojis-per-row: 8;
  --emoji-area-height: calc((var(--row-count) * var(--emoji-size) * var(--emoji-size-multiplier)) + var(--category-name-height));
  --emoji-preview-size: 2.75em;
  --emoji-preview-height: calc(var(--emoji-preview-size) + 1em + 1px);
  --emoji-preview-margin: 4px;
  --emoji-preview-height-full: calc(var(--emoji-preview-height) + var(--emoji-preview-margin));
}
</style>
<style>
:root {
  --row-count: 6;
  --category-name-height: 2rem;
  --content-height: var(--emoji-area-height);
  --category-tabs-height: calc(1.5em + 9px);
  --category-tabs-offset: 8px;
  --picker-width: calc(var(--emojis-per-row) * var(--emoji-size) * var(--emoji-size-multiplier) + 2.75rem);
  --search-height: 2em;
  --search-margin: .5em;
  --search-margin-bottom: 4px;
  --search-height-full: calc(var(--search-height) + var(--search-margin) + var(--search-margin-bottom));
}
.test {
  height: calc(var(--content-height) + var(--category-tabs-height) + var(--category-tabs-offset));
}
</style>
<style>
.test2 {
  min-height: calc(var(--emoji-size) * var(--emoji-size-multiplier));
  grid-template-columns: repeat(var(--emojis-per-row), calc(var(--emoji-size) * var(--emoji-size-multiplier)));
  grid-auto-rows: calc(var(--emoji-size) * var(--emoji-size-multiplier));
}
</style>
</head>
<body>
  <p>Hello</p>
</body>
</html>
```

![HTML validation issues](https://user-images.githubusercontent.com/864340/186847810-b18ad855-79f7-4686-9123-ca833463bea4.png)

The same extracted CSS passed to the [CSS validator](https://jigsaw.w3.org/css-validator/validator.html.en#validate_by_input) works just fine:

```css
:root {
  --emoji-size: 2rem;
  --emoji-size-multiplier: 1.3;
  --emojis-per-row: 8;
  --emoji-area-height: calc((var(--row-count) * var(--emoji-size) * var(--emoji-size-multiplier)) + var(--category-name-height));
  --emoji-preview-size: 2.75em;
  --emoji-preview-height: calc(var(--emoji-preview-size) + 1em + 1px);
  --emoji-preview-margin: 4px;
  --emoji-preview-height-full: calc(var(--emoji-preview-height) + var(--emoji-preview-margin));
}
:root {
  --row-count: 6;
  --category-name-height: 2rem;
  --content-height: var(--emoji-area-height);
  --category-tabs-height: calc(1.5em + 9px);
  --category-tabs-offset: 8px;
  --picker-width: calc(var(--emojis-per-row) * var(--emoji-size) * var(--emoji-size-multiplier) + 2.75rem);
  --search-height: 2em;
  --search-margin: .5em;
  --search-margin-bottom: 4px;
  --search-height-full: calc(var(--search-height) + var(--search-margin) + var(--search-margin-bottom));
}
.test {
  height: calc(var(--content-height) + var(--category-tabs-height) + var(--category-tabs-offset));
}
.test2 {
  min-height: calc(var(--emoji-size) * var(--emoji-size-multiplier));
  grid-template-columns: repeat(var(--emojis-per-row), calc(var(--emoji-size) * var(--emoji-size-multiplier)));
  grid-auto-rows: calc(var(--emoji-size) * var(--emoji-size-multiplier));
}
```

![CSS validator passes](https://user-images.githubusercontent.com/864340/186847640-e6b54f29-f8fa-49ca-8e6b-affc3fd4724e.png)
