### ISSUE TITLE
Unicode supplementary character in CSS content value causes parse error

### ISSUE THREAD

**Issue by skyfaller** [validator/validator#1344]
URL being validated or code to reproduce error:
```css
/* decorative text in hr at top & bottom of page */
.menu hr::after,
footer hr::after {
	background: var(--background);
	content: '🚧';
	padding: 0 .2em;
	position: relative;
	top: -.8em;
}
```
You can see this in context at: https://www.maximumethics.dev/css/style.css

```
Error: content: Parse Error.
```
If it matters, [this CSS validates on the old school validator](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fwww.maximumethics.dev%2Fcss%2Fstyle.css&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en), but [not on Nu](https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fwww.maximumethics.dev%2Fcss%2Fstyle.css).

Is it really not sufficient to [serve the CSS file as UTF-8](https://stackoverflow.com/questions/10393462/placing-unicode-character-in-css-content-value), as I'm doing? If it really [must be escaped Unicode](https://stackoverflow.com/questions/190396/adding-html-entities-using-css-content), then I apologize and you can close this bug.
