### ISSUE TITLE
has parse error

### ISSUE THREAD

**Issue by j212r** [validator/validator#1678]
URL being validated or code to reproduce error:
I tryed to check
```
table:has(td.volgnr) {
    counter-reset: sortabletablescope;
}
```

```
Error: Parse Error.
At line 2193, column 20
```
If I remove the has-part or change into "is" it's fine.

**Comment by ptriller** [comment]
My guess is there is a problem in the parsing of a "relative selector", because it works if you add the leading space, that usually starts a descendant combinator. However in this location the spec says that the usual space is not needed here and implied if omitted.
Because of that this works:
```css
table:has( td.volgnr) {
    counter-reset: sortabletablescope;
}
```
