### ISSUE TITLE
@font-feature-values CSS at-rule incorrectly marked as an error.

### ISSUE THREAD

**Issue by Electricz0** [validator/validator#1683]
Code to reproduce the error:

```CSS
@font-feature-values Fira Code {
    @character-variant {
        alt-a: 1;
        alt-g: 2;
        alt-i-1: 3;
    }
}
```

Error message:

> Error Unrecognized at-rule `@font-features-values`
> From line 1, column 1; to line 1, column 20
> `@font-feature-values {↩	@c`

![image](https://github.com/validator/validator/assets/12022661/cdb38c39-5cbd-49e3-a056-207582dbba05)
