### ISSUE TITLE
Parse error, "stroke".

### ISSUE THREAD

**Issue by martinthomson** [validator/validator#1820]
URL being validated or code to reproduce error: https://w3c.github.io/ppa/

[Output from spec-prod build](https://github.com/w3c/ppa/actions/runs/14899805586/job/41849198831?pr=155#step:3:943):
```
java -jar "/home/runner/work/_actions/w3c/spec-prod/v2/node_modules/.pnpm/vnu-jar@24.10.17/node_modules/vnu-jar/build/dist/vnu.jar" --also-check-css api.html
    "file:/home/runner/work/ppa/ppa.w3c/api.html":24.4-24.4: error: CSS: “stroke”: Parse Error.
  ❌  Not so good... please fix the issues above.
```

Actual CSS follows, though I'm not sure about how this corresponds with the reported line numbers as I don't have access to the specific file.

```css
svg.diagram {
  [stroke="black"], [stroke^="#000"] {
    stroke: var(--text);
  }
/* pattern repeats ... */
}
```

(Yes, this is a little strange, but the CSS works for that document. I'm not really looking for feedback on it.)
